cities = City.create([
   { :name => 'Київ' },
   { :name => 'Харків' },
   { :name => 'Одеса' },
   { :name => 'Дніпропетровськ' },
   { :name => 'Донецьк' },
   { :name => 'Запоріжжя' },
   { :name => 'Львів' },
   { :name => 'Кривий Ріг' },
   { :name => 'Миколаїв' },
   { :name => 'Маріуполь' },
   { :name => 'Луганськ' },
   { :name => 'Вінниця' },
   { :name => 'Макіївка' },
   { :name => 'Севастополь' },
   { :name => 'Сімферополь' },
   { :name => 'Херсон' },
   { :name => 'Полтава' },
   { :name => 'Чернігів' },
   { :name => 'Черкаси' },
   { :name => 'Житомир' },
   { :name => 'Суми' },
   { :name => 'Хмельницький' },
   { :name => 'Чернівці' },
   { :name => 'Горлівка' },
   { :name => 'Рівне' },
   { :name => 'Дніпродзержинськ' },
   { :name => 'Кіровоград' },
   { :name => 'Івано-Франківськ' },
   { :name => 'Кременчук' },
   { :name => 'Тернопіль' },
   { :name => 'Луцьк' },
   { :name => 'Біла Церква' },
   { :name => 'Краматорськ' },
   { :name => 'Мелітополь' },
   { :name => 'Керч' },
   { :name => 'Нікополь' },
   { :name => 'Ужгород' },
   { :name => 'Бердянськ' },
   { :name => 'Павлоград' },
   { :name => "Кам'янець-Подільський"}
   ]);

EventType.create([
   {name: "Birthday"},
   {name: "Wedding"},
   {name: "Presentation"},
   {name: "Conference"},
   {name: "Meeting"},
   {name: "Seminar"},
   {name: "Business Dinner"},
   {name: "Press Conference"},
   {name: "Product Launch"},
   {name: "VIP Event"},
   {name: "Theme Party"},
   {name: "Family Event"}
   ])

VenueType.create([
   {name: "Hotel"},
   {name: "Conference Center"},
   {name: "Restaurant"},
   {name: "Convention Center"},
   {name: "Theatre"},
   {name: "Rooftop"},
   {name: "Mansion"},
   {name: "Cafe"},
   {name: "Pub"},
   ])
