require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HallAttachmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HallAttachment. As you add validations to HallAttachment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HallAttachmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all hall_attachments as @hall_attachments" do
      hall_attachment = HallAttachment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:hall_attachments)).to eq([hall_attachment])
    end
  end

  describe "GET #show" do
    it "assigns the requested hall_attachment as @hall_attachment" do
      hall_attachment = HallAttachment.create! valid_attributes
      get :show, {:id => hall_attachment.to_param}, valid_session
      expect(assigns(:hall_attachment)).to eq(hall_attachment)
    end
  end

  describe "GET #new" do
    it "assigns a new hall_attachment as @hall_attachment" do
      get :new, {}, valid_session
      expect(assigns(:hall_attachment)).to be_a_new(HallAttachment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested hall_attachment as @hall_attachment" do
      hall_attachment = HallAttachment.create! valid_attributes
      get :edit, {:id => hall_attachment.to_param}, valid_session
      expect(assigns(:hall_attachment)).to eq(hall_attachment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HallAttachment" do
        expect {
          post :create, {:hall_attachment => valid_attributes}, valid_session
        }.to change(HallAttachment, :count).by(1)
      end

      it "assigns a newly created hall_attachment as @hall_attachment" do
        post :create, {:hall_attachment => valid_attributes}, valid_session
        expect(assigns(:hall_attachment)).to be_a(HallAttachment)
        expect(assigns(:hall_attachment)).to be_persisted
      end

      it "redirects to the created hall_attachment" do
        post :create, {:hall_attachment => valid_attributes}, valid_session
        expect(response).to redirect_to(HallAttachment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved hall_attachment as @hall_attachment" do
        post :create, {:hall_attachment => invalid_attributes}, valid_session
        expect(assigns(:hall_attachment)).to be_a_new(HallAttachment)
      end

      it "re-renders the 'new' template" do
        post :create, {:hall_attachment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hall_attachment" do
        hall_attachment = HallAttachment.create! valid_attributes
        put :update, {:id => hall_attachment.to_param, :hall_attachment => new_attributes}, valid_session
        hall_attachment.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested hall_attachment as @hall_attachment" do
        hall_attachment = HallAttachment.create! valid_attributes
        put :update, {:id => hall_attachment.to_param, :hall_attachment => valid_attributes}, valid_session
        expect(assigns(:hall_attachment)).to eq(hall_attachment)
      end

      it "redirects to the hall_attachment" do
        hall_attachment = HallAttachment.create! valid_attributes
        put :update, {:id => hall_attachment.to_param, :hall_attachment => valid_attributes}, valid_session
        expect(response).to redirect_to(hall_attachment)
      end
    end

    context "with invalid params" do
      it "assigns the hall_attachment as @hall_attachment" do
        hall_attachment = HallAttachment.create! valid_attributes
        put :update, {:id => hall_attachment.to_param, :hall_attachment => invalid_attributes}, valid_session
        expect(assigns(:hall_attachment)).to eq(hall_attachment)
      end

      it "re-renders the 'edit' template" do
        hall_attachment = HallAttachment.create! valid_attributes
        put :update, {:id => hall_attachment.to_param, :hall_attachment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested hall_attachment" do
      hall_attachment = HallAttachment.create! valid_attributes
      expect {
        delete :destroy, {:id => hall_attachment.to_param}, valid_session
      }.to change(HallAttachment, :count).by(-1)
    end

    it "redirects to the hall_attachments list" do
      hall_attachment = HallAttachment.create! valid_attributes
      delete :destroy, {:id => hall_attachment.to_param}, valid_session
      expect(response).to redirect_to(hall_attachments_url)
    end
  end

end
